### ISSUE TITLE
changeable plugin toggle button

### ISSUE THREAD

**Issue by SakifX9** [GrantJL/rl-lobby-ranks#1]
Not sure if this is a thing, if so I couldn't find it but I would like to be able to change the toggle button for the plugin. Right now pressing "P" opens the menu but I would like the option to disable this and only have the plugin show when I open the scoreboard etc.

**Comment by GrantJL** [comment]
With BakkesMod, you can hit `F2` and go to the `Bindings` tab. From there you can change any bakkes mod related bindings.
You can unbind the `jlg_lobby_rank_toggle` command from the `P` key here, this will resolve your issue.

I think I'll be removing this binding by default  in the future and leave it tied to the scoreboard.

**Comment by GrantJL** [comment]
Default `P` binding removed in #2.

**Comment by GrantJL** [comment]
I hadn't realized the bakkesplugin never updated with this fix.

I have updated it now, however, it looks like it is taking a while for the bakkesplugin website to update the plugin.

I have instead added a release to the GitHub page.
You can follow the install instructions there: [GitHub - LobbyRanks v1.1.4](https://github.com/GrantJL/rl-lobby-ranks/releases/tag/v1.1.4.4)

I will close this issue out now, feel free to comment here, or open another if you have further issues.
