### ISSUE TITLE
Changing the key bind doesn't save upon restarting Rocket League

### ISSUE THREAD

**Issue by nefariouslegion** [GrantJL/rl-lobby-ranks#5]
Whenever I change the keybind from P to something else (like ]) it resets the bind upon restarting rocket league. This is annoying because when I'm typing in in-game chat it opens the Lobby Ranks any time I type a P. I don't know why the keybind doesn't save

**Comment by GrantJL** [comment]
Looks like it is taking a while for the bakkesplugin website to update the plugin.

I have instead added a release to the GitHub page.
You can follow the install instructions there: [GitHub - LobbyRanks v1.1.4](https://github.com/GrantJL/rl-lobby-ranks/releases/tag/v1.1.4.4)

I will close this issue out now, feel free to comment here, or open another if you have further issues.
