### ISSUE TITLE
Opposition displays no stats

### ISSUE THREAD

**Issue by rumplesweatskin** [GrantJL/rl-lobby-ranks#6]
Its installed, but the opponent's stats are blank.

---

**Describe the defect / bug**
A clear and concise description of what the issue is.

**To Reproduce**
1. First step to cause the issue
2. Second step
3. ...
4. The issue occurs

**Expected behavior**

**Screenshots**

**Comment by GrantJL** [comment]
Does this occur everytime you play.

Currently, stats are only displayed for ranked playlists(1v1, 2v2, 3v3 and tournament), it may be possible the other team have not played ranked games, e.g. they only play casual.
Additionally, bots always have no stats

If possible a screen shot of this issue may help.

**Comment by smallest-cock** [comment]
![Same](https://github.com/GrantJL/rl-lobby-ranks/assets/48503773/0a64e4ae-a0b1-4dd9-977f-d7f8413b47ba)

Same thing happening to me...

It was working fine, then I reinstalled bakkesmod (because another plugin was causing crashes) which meant I had to reinstall all my previous plugins. After I reinstalled this plugin, opponents' ranks stopped showing up. I even tried the `jlg_lobby_rank_refresh` bakkesmod console command and nothing happens

**Comment by GrantJL** [comment]
Hmmm okay, thanks for the extra info, will look into it

**Comment by rumplesweatskin** [comment]
Turns out it was because bakkes was set to run as an admin but rocket league was not. On Aug 2, 2023, at 7:44 AM, Jayden Grant ***@***.***> wrote:﻿
Hmmm okay, thanks for the extra info, will look into it

**Comment by smallest-cock** [comment]
> Turns out it was because bakkes was set to run as an admin but rocket league was not.

@rumplesweatskin Do you remember what you did specifically to get it working again? I tried running BM as admin, RL as admin, and both as admin and I'm still getting the same issue

**Comment by smallest-cock** [comment]
Nevermind... I found out what it was

I was looking at a similar plugin and seen this

![show player mmr on scoreboard](https://github.com/GrantJL/rl-lobby-ranks/assets/48503773/ddc4a39d-0488-4de2-bd39-e371cc27dc1a)

So I toggled on those settings in BM and the plugin works fine again. Apparently when I reinstalled BM those settings got reset, which caused my issue. @GrantJL maybe you can add a disclaimer about those settings on the BakkesPlugins page or the readme

**Comment by GrantJL** [comment]
Ensure both `Show player MMR on scoreboard` and `Show MMR in casual playlist` are both check in the BakkesMods settings, under the `Ranked` tab. Without there, other player's MMR will not display correctly in the Ranked Table.
